//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCPanaderia.Models.DTOs
{
    using System;
    using System.Collections.Generic;
    
    public partial class Panadero
    {
        public int EmpleadoID { get; set; }
        public Nullable<int> ProductoID { get; set; }
        public string Nombre { get; set; }
        public string Ocupacion { get; set; }
        public string TipoPan { get; set; }
        public int Cantidad { get; set; }
        public int Stock { get; set; }
    
        public virtual Producto Producto { get; set; }
        public virtual Producto Producto1 { get; set; }
    }
}
