//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCPanaderia.Models.DTOs
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PanaderiaModel : DbContext
    {
        public PanaderiaModel()
            : base("name=PanaderiaModel")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Galletero> Galleteroes { get; set; }
        public virtual DbSet<Panadero> Panaderoes { get; set; }
        public virtual DbSet<Producto> Productos { get; set; }
        public virtual DbSet<Venta> Ventas { get; set; }
    
        public virtual int Delete_Galletero(Nullable<int> empleadoID)
        {
            var empleadoIDParameter = empleadoID.HasValue ?
                new ObjectParameter("EmpleadoID", empleadoID) :
                new ObjectParameter("EmpleadoID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Delete_Galletero", empleadoIDParameter);
        }
    
        public virtual int Delete_Panadero(Nullable<int> empleadoID)
        {
            var empleadoIDParameter = empleadoID.HasValue ?
                new ObjectParameter("EmpleadoID", empleadoID) :
                new ObjectParameter("EmpleadoID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Delete_Panadero", empleadoIDParameter);
        }
    
        public virtual int Delete_Producto(Nullable<int> productoID)
        {
            var productoIDParameter = productoID.HasValue ?
                new ObjectParameter("ProductoID", productoID) :
                new ObjectParameter("ProductoID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Delete_Producto", productoIDParameter);
        }
    
        public virtual int Delete_Venta(Nullable<int> ventaID)
        {
            var ventaIDParameter = ventaID.HasValue ?
                new ObjectParameter("VentaID", ventaID) :
                new ObjectParameter("VentaID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Delete_Venta", ventaIDParameter);
        }
    
        public virtual int Delete_Venta_Diaria(Nullable<int> ventaDiariaID)
        {
            var ventaDiariaIDParameter = ventaDiariaID.HasValue ?
                new ObjectParameter("VentaDiariaID", ventaDiariaID) :
                new ObjectParameter("VentaDiariaID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Delete_Venta_Diaria", ventaDiariaIDParameter);
        }
    
        public virtual int Insert_Galletero(Nullable<int> productoID, string nombre, string ocupacion, string tipoGalleta, Nullable<int> cantidad, Nullable<int> stock)
        {
            var productoIDParameter = productoID.HasValue ?
                new ObjectParameter("ProductoID", productoID) :
                new ObjectParameter("ProductoID", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var ocupacionParameter = ocupacion != null ?
                new ObjectParameter("Ocupacion", ocupacion) :
                new ObjectParameter("Ocupacion", typeof(string));
    
            var tipoGalletaParameter = tipoGalleta != null ?
                new ObjectParameter("TipoGalleta", tipoGalleta) :
                new ObjectParameter("TipoGalleta", typeof(string));
    
            var cantidadParameter = cantidad.HasValue ?
                new ObjectParameter("Cantidad", cantidad) :
                new ObjectParameter("Cantidad", typeof(int));
    
            var stockParameter = stock.HasValue ?
                new ObjectParameter("Stock", stock) :
                new ObjectParameter("Stock", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Insert_Galletero", productoIDParameter, nombreParameter, ocupacionParameter, tipoGalletaParameter, cantidadParameter, stockParameter);
        }
    
        public virtual int Insert_Panadero(Nullable<int> productoID, string nombre, string ocupacion, string tipoPan, Nullable<int> cantidad, Nullable<int> stock)
        {
            var productoIDParameter = productoID.HasValue ?
                new ObjectParameter("ProductoID", productoID) :
                new ObjectParameter("ProductoID", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var ocupacionParameter = ocupacion != null ?
                new ObjectParameter("Ocupacion", ocupacion) :
                new ObjectParameter("Ocupacion", typeof(string));
    
            var tipoPanParameter = tipoPan != null ?
                new ObjectParameter("TipoPan", tipoPan) :
                new ObjectParameter("TipoPan", typeof(string));
    
            var cantidadParameter = cantidad.HasValue ?
                new ObjectParameter("Cantidad", cantidad) :
                new ObjectParameter("Cantidad", typeof(int));
    
            var stockParameter = stock.HasValue ?
                new ObjectParameter("Stock", stock) :
                new ObjectParameter("Stock", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Insert_Panadero", productoIDParameter, nombreParameter, ocupacionParameter, tipoPanParameter, cantidadParameter, stockParameter);
        }
    
        public virtual int Insert_Producto(string nombreProducto, string tipoProducto)
        {
            var nombreProductoParameter = nombreProducto != null ?
                new ObjectParameter("NombreProducto", nombreProducto) :
                new ObjectParameter("NombreProducto", typeof(string));
    
            var tipoProductoParameter = tipoProducto != null ?
                new ObjectParameter("TipoProducto", tipoProducto) :
                new ObjectParameter("TipoProducto", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Insert_Producto", nombreProductoParameter, tipoProductoParameter);
        }
    
        public virtual int Insert_Venta(Nullable<int> productoID, Nullable<int> cantidad, Nullable<decimal> precio)
        {
            var productoIDParameter = productoID.HasValue ?
                new ObjectParameter("ProductoID", productoID) :
                new ObjectParameter("ProductoID", typeof(int));
    
            var cantidadParameter = cantidad.HasValue ?
                new ObjectParameter("Cantidad", cantidad) :
                new ObjectParameter("Cantidad", typeof(int));
    
            var precioParameter = precio.HasValue ?
                new ObjectParameter("Precio", precio) :
                new ObjectParameter("Precio", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Insert_Venta", productoIDParameter, cantidadParameter, precioParameter);
        }
    
        public virtual int Insert_Venta_Diaria(Nullable<int> ventaID, Nullable<System.DateTime> fecha, Nullable<decimal> total)
        {
            var ventaIDParameter = ventaID.HasValue ?
                new ObjectParameter("VentaID", ventaID) :
                new ObjectParameter("VentaID", typeof(int));
    
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("Fecha", fecha) :
                new ObjectParameter("Fecha", typeof(System.DateTime));
    
            var totalParameter = total.HasValue ?
                new ObjectParameter("Total", total) :
                new ObjectParameter("Total", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Insert_Venta_Diaria", ventaIDParameter, fechaParameter, totalParameter);
        }
    
        public virtual ObjectResult<Obtener_Galleteros_Result> Obtener_Galleteros()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Obtener_Galleteros_Result>("Obtener_Galleteros");
        }
    
        public virtual ObjectResult<Obtener_Panaderos_Result> Obtener_Panaderos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Obtener_Panaderos_Result>("Obtener_Panaderos");
        }
    
        public virtual ObjectResult<Obtener_Productos_Result> Obtener_Productos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Obtener_Productos_Result>("Obtener_Productos");
        }
    
        public virtual ObjectResult<Obtener_Ventas_Result> Obtener_Ventas()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Obtener_Ventas_Result>("Obtener_Ventas");
        }
    
        public virtual int Obtener_Ventas_Diarias()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Obtener_Ventas_Diarias");
        }
    
        public virtual ObjectResult<ObtenerVentaPorDatos_Result> ObtenerVentaPorDatos(Nullable<int> productoID)
        {
            var productoIDParameter = productoID.HasValue ?
                new ObjectParameter("ProductoID", productoID) :
                new ObjectParameter("ProductoID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ObtenerVentaPorDatos_Result>("ObtenerVentaPorDatos", productoIDParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual int Update_Galletero(Nullable<int> empleadoID, Nullable<int> productoID, string nombre, string ocupacion, string tipoGalleta, Nullable<int> cantidad, Nullable<int> stock)
        {
            var empleadoIDParameter = empleadoID.HasValue ?
                new ObjectParameter("EmpleadoID", empleadoID) :
                new ObjectParameter("EmpleadoID", typeof(int));
    
            var productoIDParameter = productoID.HasValue ?
                new ObjectParameter("ProductoID", productoID) :
                new ObjectParameter("ProductoID", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var ocupacionParameter = ocupacion != null ?
                new ObjectParameter("Ocupacion", ocupacion) :
                new ObjectParameter("Ocupacion", typeof(string));
    
            var tipoGalletaParameter = tipoGalleta != null ?
                new ObjectParameter("TipoGalleta", tipoGalleta) :
                new ObjectParameter("TipoGalleta", typeof(string));
    
            var cantidadParameter = cantidad.HasValue ?
                new ObjectParameter("Cantidad", cantidad) :
                new ObjectParameter("Cantidad", typeof(int));
    
            var stockParameter = stock.HasValue ?
                new ObjectParameter("Stock", stock) :
                new ObjectParameter("Stock", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Update_Galletero", empleadoIDParameter, productoIDParameter, nombreParameter, ocupacionParameter, tipoGalletaParameter, cantidadParameter, stockParameter);
        }
    
        public virtual int Update_Panadero(Nullable<int> empleadoID, Nullable<int> productoID, string nombre, string ocupacion, string tipoPan, Nullable<int> cantidad, Nullable<int> stock)
        {
            var empleadoIDParameter = empleadoID.HasValue ?
                new ObjectParameter("EmpleadoID", empleadoID) :
                new ObjectParameter("EmpleadoID", typeof(int));
    
            var productoIDParameter = productoID.HasValue ?
                new ObjectParameter("ProductoID", productoID) :
                new ObjectParameter("ProductoID", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var ocupacionParameter = ocupacion != null ?
                new ObjectParameter("Ocupacion", ocupacion) :
                new ObjectParameter("Ocupacion", typeof(string));
    
            var tipoPanParameter = tipoPan != null ?
                new ObjectParameter("TipoPan", tipoPan) :
                new ObjectParameter("TipoPan", typeof(string));
    
            var cantidadParameter = cantidad.HasValue ?
                new ObjectParameter("Cantidad", cantidad) :
                new ObjectParameter("Cantidad", typeof(int));
    
            var stockParameter = stock.HasValue ?
                new ObjectParameter("Stock", stock) :
                new ObjectParameter("Stock", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Update_Panadero", empleadoIDParameter, productoIDParameter, nombreParameter, ocupacionParameter, tipoPanParameter, cantidadParameter, stockParameter);
        }
    
        public virtual int Update_Producto(Nullable<int> productoID, string nombreProducto, string tipoProducto)
        {
            var productoIDParameter = productoID.HasValue ?
                new ObjectParameter("ProductoID", productoID) :
                new ObjectParameter("ProductoID", typeof(int));
    
            var nombreProductoParameter = nombreProducto != null ?
                new ObjectParameter("NombreProducto", nombreProducto) :
                new ObjectParameter("NombreProducto", typeof(string));
    
            var tipoProductoParameter = tipoProducto != null ?
                new ObjectParameter("TipoProducto", tipoProducto) :
                new ObjectParameter("TipoProducto", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Update_Producto", productoIDParameter, nombreProductoParameter, tipoProductoParameter);
        }
    
        public virtual int Update_Venta(Nullable<int> ventaID, Nullable<int> productoID, Nullable<int> cantidad, Nullable<decimal> precio)
        {
            var ventaIDParameter = ventaID.HasValue ?
                new ObjectParameter("VentaID", ventaID) :
                new ObjectParameter("VentaID", typeof(int));
    
            var productoIDParameter = productoID.HasValue ?
                new ObjectParameter("ProductoID", productoID) :
                new ObjectParameter("ProductoID", typeof(int));
    
            var cantidadParameter = cantidad.HasValue ?
                new ObjectParameter("Cantidad", cantidad) :
                new ObjectParameter("Cantidad", typeof(int));
    
            var precioParameter = precio.HasValue ?
                new ObjectParameter("Precio", precio) :
                new ObjectParameter("Precio", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Update_Venta", ventaIDParameter, productoIDParameter, cantidadParameter, precioParameter);
        }
    
        public virtual int Update_Venta_Diaria(Nullable<int> ventaDiariaID, Nullable<int> ventaID, Nullable<System.DateTime> fecha, Nullable<decimal> total)
        {
            var ventaDiariaIDParameter = ventaDiariaID.HasValue ?
                new ObjectParameter("VentaDiariaID", ventaDiariaID) :
                new ObjectParameter("VentaDiariaID", typeof(int));
    
            var ventaIDParameter = ventaID.HasValue ?
                new ObjectParameter("VentaID", ventaID) :
                new ObjectParameter("VentaID", typeof(int));
    
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("Fecha", fecha) :
                new ObjectParameter("Fecha", typeof(System.DateTime));
    
            var totalParameter = total.HasValue ?
                new ObjectParameter("Total", total) :
                new ObjectParameter("Total", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Update_Venta_Diaria", ventaDiariaIDParameter, ventaIDParameter, fechaParameter, totalParameter);
        }
    }
}
